default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: st_data_development
  schema_search_path: public

test:
  <<: *default
  database: st_data_test
  schema_search_path: public
